---
image: golang:1.24.2

stages:
  - test

default:
  timeout: 10 minutes

# Check that all packages are compiling.
build:
  stage: test
  script:
    - make build
  only:
    - branches

# Check that all integration tests are labeled.
test-short:
  stage: test
  script:
    - make test-short
  only:
    - branches

# Runs all test.
test:
  services:
    - docker:dind
  stage: test
  variables:
    DOCKER_HOST: tcp://docker:2375
    TESTING_DB_URL: postgresql://postgres:postgres@docker:32260/postgres?sslmode=disable
  before_script:
    - curl -fsSL https://get.docker.com -o install-docker.sh
    - sh install-docker.sh
    - docker version
    - docker compose version
    - make test-env-up
  script:
    - make test
    - go get github.com/boumenot/gocover-cobertura
    - go run github.com/boumenot/gocover-cobertura < coverage.out > coverage.xml
  after_script:
    - make test-env-down
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
  coverage: /^total:\s+\(statements\)\s+(\d+(?:\.\d+)?%)/
  only:
    - branches

# Check actuality of go.mod and go.sum
#
# See https://xorcare.ru/s/8dd13
check-go-modules:
  stage: test
  script:
    - go mod tidy
    - |
      git diff --exit-code && exit 0 || true
      echo -e "\033[0;31m"
      echo '######################################################################'
      echo
      echo "ERROR: go.mod or go.sum is different from the committed version"
      echo "Try using 'go mod tidy' to fix the go.mod and go.sum files"
      echo "Also, don't forget to commit and push changes"
      echo
      echo '######################################################################'
      exit 1
