linters:
  disable-all: true
  enable:
    - errcheck
    - godot
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - testifylint
    - testpackage
    - typecheck
    - unused
    - whitespace
    - wsl

linters-settings:
  goimports:
    local-prefixes: github.com/xorcare/testing-go-code-with-postgres
  unused:
    field-writes-are-uses: false
    post-statements-are-reads: true
    exported-fields-are-used: false
    local-variables-are-used: false
