name: GitLab

on:
  push:
  workflow_dispatch:

jobs:
  mirror:
    name: Mirroring to GitLab
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Mirror repository to Gitlab
        run: |
          set -e -x
          ssh-keyscan -H "${{ vars.GITLAB_HOSTNAME }}" | tee -a ~/.ssh/known_hosts
          git remote add gitlab "${{ vars.GITLAB_REPO_SSH }}"
          git push --force gitlab "$GITHUB_REF_NAME"
